# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 493ce253a653709d9b1bb34d10a3082b8c359e6ddc7f898104231ddff999e3627ed6e1dd886483907961476cbbc5eaacaee28cdd69668b76419eff996bd24700

test:
  secret_key_base: 379cbdd85400bed088d6c92c9603a4239cf1eb55836e57065e656feae4dbe830892e92bdd6d9a00766e9d429dc4887f5a60d95ab57ef99b6c70575fa0be447c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
